# -*- coding: utf-8 -*-
"""Analysis of Explanation Effects on Trust.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ds3dFp8YN17zUUAL_uz00YMmlH-TghLq

---
#  **Statistical analysis in R**

**Developer:**

*   Rayele Moreira
*   Adonias Caetano de Oliveira
*   Ariel Soares Teles

**Title:** "Analysis of Explanation Effects on Trust"

---

## **1 - General settings**
"""

#Define seed to ensure reproducibility
set.seed(123)

# Create subfolders within the outputs for organization.
dir.create("outputs", showWarnings = FALSE)
dir.create("outputs/tables", showWarnings = FALSE, recursive = TRUE)
dir.create("outputs/figures", showWarnings = FALSE, recursive = TRUE)

"""## **2 - Installation and loading of packages**"""

# - tidyverse: data manipulation and visualization (dplyr, ggplot2, tidyr, etc.)
# - readr: efficient CSV reading
# - janitor: standardizes column names (clean_names)
# - lme4 + lmerTest: linear mixed models + approximate p-value
# - emmeans: estimated marginal means and contrasts (CoT - Non-CoT)
# - broom.mixed: organizes model results in table format
# - performance: model checks/diagnostics
pkgs <- c("tidyverse", "readr", "janitor", "lme4", "lmerTest", "emmeans", "broom.mixed", "performance")
install.packages(pkgs)

"""## **3 - Load the packages**"""

library(tidyverse)
library(readr)
library(janitor)
library(lme4)
library(lmerTest)
library(emmeans)
library(broom.mixed)
library(performance)

"""## **4 - Data import and preparation**"""

# carregando o arquivo
df_raw <- readr::read_csv("data/data.csv") %>%
janitor::clean_names()

# analisando estrutura geral do dataset
glimpse(df_raw)
names(df_raw)

# Data preparation
df <- df_raw %>%
  dplyr::mutate(
    # ID as a factor (essential for (1|id))
    id = as.factor(id),

    # Condition as a factor, with Non-CoT as a reference.
    type_of_explanation = factor(type_of_explanation, levels = c("Non-CoT", "CoT")),

    # Ensure that the Likert outcomes are numerical.
    trust = as.numeric(trust),
    consistency = as.numeric(consistency),
    understanding = as.numeric(understanding),
    relevance = as.numeric(relevance)
  )

# Checklist: each participant must have 2 lines (CoT and Non-CoT)
rows_per_id <- df %>%
  dplyr::count(id, name = "n_rows")

# Visualize if anyone is acting out of the expected behavior.
rows_per_id %>% dplyr::count(n_rows)

"""### **5 - Descriptive Statistics**

**Table 1 - Descriptives by Condition**
"""

outcomes <- c("trust", "consistency", "understanding", "relevance")

desc_tbl <- df %>%
  tidyr::pivot_longer(cols = all_of(outcomes), names_to = "Outcome", values_to = "Score") %>%
  dplyr::group_by(Outcome, type_of_explanation) %>%
  dplyr::summarise(
    N = sum(!is.na(Score)),
    Mean = mean(Score, na.rm = TRUE),
    SD = sd(Score, na.rm = TRUE),
    Median = median(Score, na.rm = TRUE),
    IQR = IQR(Score, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  dplyr::mutate(
    Outcome = stringr::str_to_title(Outcome),
    Condition = as.character(type_of_explanation)
  ) %>%
  dplyr::select(Outcome, Condition, N, Mean, SD, Median, IQR)

readr::write_csv(desc_tbl, "outputs/tables/Table1_Descriptives_byCondition.csv")
desc_tbl

"""**Descriptive statistics**

Across outcomes, ratings were high in both conditions (means approximately 4.2–4.6 on a 1–5 scale). For all outcomes, the CoT condition showed higher mean and median scores than the Non-CoT condition. The largest descriptive difference was observed for Consistency (Non-CoT: M = 4.24, SD = 0.76, median = 4.4; CoT: M = 4.48, SD = 0.60, median = 4.8), whereas differences were smaller for Trust (Non-CoT: M = 4.25; CoT: M = 4.37), Understanding (Non-CoT: M = 4.45; CoT: M = 4.62), and Relevance (Non-CoT: M = 4.22; CoT: M = 4.42).

### **5.1. Ditributions**
"""

# Figure 1 - Distributions by Condition
p_box <- df %>%
  tidyr::pivot_longer(cols = all_of(outcomes), names_to = "Outcome", values_to = "Score") %>%
  dplyr::mutate(Outcome = stringr::str_to_title(Outcome)) %>%
  ggplot2::ggplot(ggplot2::aes(x = type_of_explanation, y = Score)) +
  ggplot2::geom_boxplot() +
  ggplot2::facet_wrap(~ Outcome, ncol = 2) +
  ggplot2::labs(
    title = "Distributions by Condition",
    x = "Condition",
    y = "Likert Score (1–5)"
  )

ggplot2::ggsave("outputs/figures/Figure1_Distributions_byCondition.png", p_box,
                width = 9, height = 6, dpi = 300)

p_box

dir.create("outputs/figures", recursive = TRUE, showWarnings = FALSE)

p_box_pretty <- df %>%
  pivot_longer(cols = all_of(outcomes), names_to = "Outcome", values_to = "Score") %>%
  mutate(
    Outcome = str_to_title(Outcome),
    Condition = factor(type_of_explanation, levels = c("Non-CoT", "CoT"))
  ) %>%
  ggplot(aes(x = Condition, y = Score, fill = Condition)) +
  geom_boxplot(
    width = 0.6,
    outlier.shape = 16,
    outlier.alpha = 0.6
  ) +
  facet_wrap(~ Outcome, ncol = 2) +
  scale_fill_brewer(palette = "Set2") +
  labs(
    title = "Distributions by Condition",
    x = "Condition",
    y = "Likert score (1–5)"
  ) +
  theme_minimal(base_size = 13) +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold", size = 16),
    strip.text = element_text(face = "bold", size = 12),
    legend.position = "none",
    panel.grid.minor = element_blank()
  )

ggsave("outputs/figures/Figure1_Boxplot_Pretty.png",
       p_box_pretty, width = 10, height = 6.5, dpi = 300)

p_box_pretty

p_violin <- df %>%
  pivot_longer(cols = all_of(outcomes), names_to = "Outcome", values_to = "Score") %>%
  mutate(
    Outcome = str_to_title(Outcome),
    Condition = factor(type_of_explanation, levels = c("Non-CoT", "CoT"))
  ) %>%
  ggplot(aes(x = Condition, y = Score, fill = Condition)) +
  geom_violin(trim = FALSE, alpha = 0.55) +
  geom_boxplot(width = 0.18, outlier.shape = NA, alpha = 0.85) +
  geom_jitter(aes(color = Condition),
              width = 0.08, alpha = 0.35, size = 1.2) +
  facet_wrap(~ Outcome, ncol = 2) +
  scale_fill_brewer(palette = "Set2") +
  scale_color_brewer(palette = "Dark2") +
  labs(
    title = "Participant Ratings by Condition",
    subtitle = "Violin plots with embedded boxplots and individual responses",
    x = "Condition",
    y = "Likert score (1–5)"
  ) +
  coord_cartesian(ylim = c(1, 5)) +
  theme_minimal(base_size = 13) +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold", size = 16),
    plot.subtitle = element_text(hjust = 0.5, size = 11),
    strip.text = element_text(face = "bold", size = 12),
    legend.position = "none",
    panel.grid.minor = element_blank()
  )

ggsave("outputs/figures/Figure1_Violin_Box_Jitter.png",
       p_violin, width = 10, height = 7.2, dpi = 300)

p_violin

p_journal <- df %>%
  pivot_longer(cols = all_of(outcomes), names_to = "Outcome", values_to = "Score") %>%
  mutate(
    Outcome = str_to_title(Outcome),
    Condition = factor(type_of_explanation, levels = c("Non-CoT", "CoT"))
  ) %>%
  ggplot(aes(x = Condition, y = Score)) +
  geom_boxplot(width = 0.5) +
  geom_jitter(width = 0.08, alpha = 0.25, size = 1.1) +
  facet_wrap(~ Outcome, ncol = 2) +
  labs(
    title = "Ratings by Condition",
    x = NULL,
    y = "Likert score (1–5)"
  ) +
  theme_classic(base_size = 13) +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold", size = 16),
    strip.background = element_blank(),
    strip.text = element_text(face = "bold", size = 12)
  )

ggsave("outputs/figures/Figure1_JournalStyle.png",
       p_journal, width = 10, height = 6.5, dpi = 300)

p_journal

"""### **(A) Consistency**

- CoT has a higher median than Non-CoT.  
- The CoT box is more concentrated around 4.5–5. This suggests that CoT was perceived as more consistent.  
- This suggests that CoT was perceived as more consistent.

### **(B) Relevance**

- Again, CoT is slightly higher than Non-CoT.  
- Non-CoT has more low outliers (people giving very poor ratings).  
- This suggests that CoT was considered more relevant, or at least had fewer extremely negative evaluations.

### **(C) Trust**

- CoT’s median is greater than Non-CoT’s, but the difference appears smaller than in Consistency.  
- Both are high (many 4–5 ratings).  
- This suggests a slight gain in trust with CoT, but with a strong ceiling effect (many 5s).

### **(D) Understanding**

- Here the difference is clearer: CoT is higher (greater median and the entire box shifted upward).  
- CoT improves the perception of understanding more strongly.

## **6 - Primary Analysis: LLM per outcome (Table 2)**
"""

# Table 2 - Linear Mixed-Effects Models (LMM): CoT vs Non-CoT
#Em média, quanto a condição CoT aumenta (ou diminui) o desfecho em relação à Non-CoT, e isso é estatisticamente significativo?

fit_lmm <- function(data, y) {
  fml <- stats::as.formula(paste0(y, " ~ type_of_explanation + (1 | id)"))
  lme4::lmer(fml, data = data, REML = FALSE)
}

models <- setNames(lapply(outcomes, \(y) fit_lmm(df, y)), outcomes)

extract_contrast <- function(model, outcome_name) {
  emm <- emmeans::emmeans(model, ~ type_of_explanation)
  ctr <- emmeans::contrast(emm, method = "revpairwise")  # CoT - Non-CoT
  as.data.frame(summary(ctr, infer = TRUE)) %>%
    dplyr::mutate(Outcome = stringr::str_to_title(outcome_name)) %>%
    dplyr::rename(
      Contrast = contrast,
      Estimate = estimate,
      SE = SE,
      DF = df,
      CI_Lower = lower.CL,
      CI_Upper = upper.CL,
      T_value = t.ratio,
      P_value = p.value
    ) %>%
    dplyr::select(Outcome, Contrast, Estimate, SE, DF, CI_Lower, CI_Upper, T_value, P_value)
}

lmm_tbl <- dplyr::bind_rows(lapply(names(models), \(nm) extract_contrast(models[[nm]], nm))) %>%
  dplyr::mutate(
    OutcomeRole = dplyr::if_else(Outcome == "Trust", "Primary", "Secondary/Exploratory")
  )

secondary <- lmm_tbl %>%
  dplyr::filter(Outcome != "Trust") %>%
  dplyr::mutate(P_Holm = stats::p.adjust(P_value, method = "holm"))

lmm_tbl_final <- lmm_tbl %>%
  dplyr::filter(Outcome == "Trust") %>%
  dplyr::mutate(P_Holm = NA_real_) %>%
  dplyr::bind_rows(secondary) %>%
  dplyr::arrange(match(tolower(Outcome), outcomes))

readr::write_csv(lmm_tbl_final, "outputs/tables/Table2_LMM_ConditionEffect.csv")
lmm_tbl_final

"""**CCondition effects (CoT vs. Non-CoT).**

For the primary outcome (Trust), there was no statistically significant effect of condition (CoT − Non-CoT: estimate = 0.12, SE = 0.12, *t*(44.02) = 1.02, *p* = .313; 95% CI \[−0.12, 0.36\]). For secondary outcomes, Consistency was significantly higher in the CoT condition (estimate = 0.24, SE = 0.10, *t*(44.02) = 2.51, *p* = .016), and this effect remained significant after correcting for multiple comparisons using Holm’s procedure (adjusted *p* = .047). Understanding and Relevance were directionally higher under CoT but did not reach statistical significance after correction (Understanding: estimate = 0.17, *p* = .078, adjusted *p* = .157; Relevance: estimate = 0.20, *p* = .084, adjusted *p* = .157).

| Outcome       | Δ (CoT−Non-CoT) | SE   | t(df)        | 95% CI      | p    | pHolm |
|---------------|-----------------|------|--------------|-------------|------|-------|
| Trust         | 0.12            | 0.12 | 1.02 (44.02) | −0.12, 0.36 | .313 | —     |
| Consistency   | 0.24            | 0.10 | 2.51 (44.02) | 0.05, 0.44  | .016 | .047  |
| Understanding | 0.17            | 0.09 | 1.80 (44.02) | −0.02, 0.35 | .078 | .157  |
| Relevance     | 0.20            | 0.11 | 1.77 (44.02) | −0.03, 0.43 | .084 | .157  |

**Comparing this to what we saw in the boxplots**

Visual inspection of boxplots suggested consistently higher ratings in the CoT condition across outcomes. Model-based comparisons supported this directional pattern; however, only Consistency differed significantly after Holm correction.

### **6.1 - Diagnosis**
"""

#| include: false
# ============================================================
# Model diagnostics (internal checks + saved outputs)
# ============================================================
# This block performs basic checks on the models (LMM) to ensure that
# the conclusions do not rely on major violations (e.g., highly
# skewed residuals, severe heteroscedasticity, extreme points).
#
# Important:
# - include: false -> does not appear in the report
# - Outputs are saved in outputs/ for consultation and/or supplement.

# 1) Create the folder where we will save the diagnoses (if it doesn't already exist).
dir.create("outputs/figures/diagnostics", showWarnings = FALSE, recursive = TRUE)
dir.create("outputs/tables", showWarnings = FALSE, recursive = TRUE)

# 2) Function to save "paper-friendly" diagnostic graphs
# (cleaner than trying to save directly check_model())
save_lmm_diagnostics <- function(model, outcome_label) {

  # Extracts fitted values ​​and residuals from the model.
  d <- data.frame(
    fitted = fitted(model),
    resid = resid(model)
  )

  # --- Plot A: Residuals vs Fitted (detects patterns and heteroscedasticity) ---
  p1 <- ggplot2::ggplot(d, ggplot2::aes(x = fitted, y = resid)) +
    ggplot2::geom_point() +
    ggplot2::geom_hline(yintercept = 0) +
    ggplot2::labs(
      title = paste0("Residuals vs Fitted (", outcome_label, ")"),
      x = "Fitted values",
      y = "Residuals"
    )

  ggplot2::ggsave(
    filename = paste0("outputs/figures/diagnostics/Diag_ResidualsFitted_", outcome_label, ".png"),
    plot = p1,
    width = 7, height = 5, dpi = 300
  )

  # --- Plot B: Normal Q-Q plot (assesses approximate normality of residues)) ---
  qq <- stats::qqnorm(d$resid, plot.it = FALSE)
  qq_df <- data.frame(theoretical = qq$x, sample = qq$y)

  p2 <- ggplot2::ggplot(qq_df, ggplot2::aes(x = theoretical, y = sample)) +
    ggplot2::geom_point() +
    ggplot2::geom_abline() +
    ggplot2::labs(
      title = paste0("Normal Q-Q Plot (", outcome_label, ")"),
      x = "Theoretical quantiles",
      y = "Sample quantiles"
    )

  ggplot2::ggsave(
    filename = paste0("outputs/figures/diagnostics/Diag_QQ_", outcome_label, ".png"),
    plot = p2,
    width = 7, height = 5, dpi = 300
  )
}

# 3) Function to save a “textual” summary of the checks (in English)
# performance::check_* returns objects with useful printability.
save_checks_text <- function(model, outcome_label) {

  norm <- performance::check_normality(model)
  hetero <- performance::check_heteroscedasticity(model)

  # Saves the printed output to a .txt file (useful for add-ins).
  capture.output(
    cat("Diagnostics Summary (", outcome_label, ")\n", sep = ""),
    cat("\n--- Normality check ---\n"),
    print(norm),
    cat("\n--- Heteroscedasticity check ---\n"),
    print(hetero),
    file = paste0("outputs/tables/Diagnostics_", outcome_label, ".txt")
  )
}

# 4) Which models to check?
# I recommend at least Trust (primary) and any outcome that gives significance (e.g., Consistency)
# Here we will check Trust and Consistency, as you were doing.
save_lmm_diagnostics(models[["trust"]], "Trust")
save_checks_text(models[["trust"]], "Trust")

save_lmm_diagnostics(models[["consistency"]], "Consistency")
save_checks_text(models[["consistency"]], "Consistency")

# Model diagnostics: show in RStudio + save the same plots
dir.create("outputs/figures/diagnostics", showWarnings = FALSE, recursive = TRUE)

save_and_show_check_model <- function(model, filename, width_px = 2400, height_px = 1800, res = 300) {
  # 1) Mostra no ambiente (RStudio Plots/Viewer)
  performance::check_model(model)

  # 2) Salva exatamente o que check_model desenha
  png(filename, width = width_px, height = height_px, res = res)
  performance::check_model(model)
  dev.off()
}

# Trust
save_and_show_check_model(
  model = models[["trust"]],
  filename = "outputs/figures/diagnostics/CheckModel_Trust.png"
)

# Consistency
save_and_show_check_model(
  model = models[["consistency"]],
  filename = "outputs/figures/diagnostics/CheckModel_Consistency.png"
)

"""#### (A) Posterior predictive check

The simulated/modeled curves (blue) closely match the observed curve (green).

This suggests a good overall fit of the predicted vs. observed distribution.

#### (B) Linearity (residuals vs. fitted)

Ideal: horizontal green line around 0.

In the graph, there is a curvature (the green line rises and then "flattens").

This suggests slight non-linearity/systematic pattern in the residuals.

This does not mean the model is "wrong," but suggests:

- ceiling effect (many 5s)

- ordinal scale

- possible compression of fitted values ​​at the top

#### (C) Homogeneity of variance

Ideal: horizontal green line.

In the graph, the green line descends as fitted increases.

This suggests mild/moderate heteroscedasticity (variance changes with fitted).

So: it is not correct to state “no evidence of heteroscedasticity” based on this figure.

It suggests the opposite: “some evidence”.

#### (D) Influential observations

There are some numbered points (e.g., 47, 49, 85, etc.), but they appear close to the contour lines and with high leverage because the fitted points are compressed.

Interpretation:

- There are potentially influential observations, but nothing indicates an extremely problematic case (such as points that are very far off).

- The correct way to say it is that you checked and that there was no undue influence (if your results did not change when removing them).

#### (E) Normality of residuals

The points deviate from the “ideal pattern”.

Non-normal residuals (expected for Likert + ceiling effect).

#### (F) Normality of random effects (id)

Points approximately follow the line, with some dispersion.

Random effects reasonably okay.

Model assumptions were evaluated using residual diagnostics and model-checking plots (Figure X). For both Trust and Consistency, residuals deviated from normality, which is expected given the bounded, ordinal (Likert-type) outcomes and the presence of ceiling effects. Visual inspection suggested mild departures from linearity and homoscedasticity; however, no severe patterns indicative of major model misspecification were observed. Importantly, conclusions were robust in sensitivity analyzes using nonparametric approaches. Overall, the linear mixed-effects model estimates were considered appropriate for inference.

Caption

**Figure X. Diagnostic plots for the linear mixed-effects models (Trust and Consistency)**
Diagnostic plots include simulated versus observed distribution checks, residuals versus fitted values ​​(linearity), scale-location plots (homoscedasticity), leverage/influence diagnostics, and Q–Q plots for residuals and random effects.

## **7 - Sensitivity: Paired Wilcoxon**
"""

# Sensitivity - Paired Wilcoxon signed-rank tests
wide <- df %>%
  dplyr::select(id, type_of_explanation, all_of(outcomes)) %>%
  tidyr::pivot_wider(
    names_from = type_of_explanation,
    values_from = all_of(outcomes),
    names_sep = "_"
  )
wilcox_paired <- function(wide_data, y) {
  x <- wide_data[[paste0(y, "_CoT")]]
  z <- wide_data[[paste0(y, "_Non-CoT")]]

  ok <- stats::complete.cases(x, z)
  x <- x[ok]; z <- z[ok]

  if (length(x) < 2) {
    return(tibble::tibble(Outcome = stringr::str_to_title(y), N_Pairs = length(x), P_value = NA_real_))
  }

  wt <- suppressWarnings(stats::wilcox.test(x, z, paired = TRUE, exact = FALSE))
  tibble::tibble(Outcome = stringr::str_to_title(y), N_Pairs = length(x), P_value = wt$p.value)
}

wilcox_tbl <- dplyr::bind_rows(lapply(outcomes, \(y) wilcox_paired(wide, y))) %>%
  dplyr::mutate(
    OutcomeRole = dplyr::if_else(Outcome == "Trust", "Primary", "Secondary/Exploratory")
  )

wilcox_secondary <- wilcox_tbl %>%
  dplyr::filter(Outcome != "Trust") %>%
  dplyr::mutate(P_Holm = stats::p.adjust(P_value, method = "holm"))

wilcox_tbl_final <- wilcox_tbl %>%
  dplyr::filter(Outcome == "Trust") %>%
  dplyr::mutate(P_Holm = NA_real_) %>%
  dplyr::bind_rows(wilcox_secondary) %>%
  dplyr::arrange(match(tolower(Outcome), outcomes))

readr::write_csv(wilcox_tbl_final, "outputs/tables/Sensitivity_Wilcoxon_Paired.csv")
wilcox_tbl_final

"""**Sensitivity analyses**

Paired Wilcoxon signed-rank tests were conducted as nonparametric sensitivity analyses to corroborate the mixed-effects results. No significant difference between CoT and Non-CoT was observed for *Trust* (p = 0.27). After correction for multiple comparisons using the Holm method, only *Consistency* remained significantly higher in the CoT condition (adjusted p = 0.044). Differences in *Understanding* and *Relevance* did not remain statistically significant after correction.

### **8 - Conditional exploratory: Trust \~ Consistency (only if only Consistency differs)**
"""

# Exploratory association (non-causal): within-person change
# Question:
# "When Consistency increases from Non-CoT to CoT within the same person,
#  does Trust also tend to increase?"
#
# Why this approach?
# - Respects the paired design directly.
# - Avoids singular-fit issues in random-intercept models when variance ~ 0.
# - Produces a clean, interpretable estimate for exploratory interpretation.

sig_tbl <- lmm_tbl_final %>%
  dplyr::mutate(
    Significant = dplyr::case_when(
      Outcome == "Trust" ~ (P_value < 0.05),
      TRUE ~ (!is.na(P_Holm) & P_Holm < 0.05)
    )
  ) %>%
  dplyr::select(Outcome, Significant, P_value, P_Holm)

only_consistency_sig <- with(sig_tbl,
  Significant[Outcome == "Consistency"] == TRUE &&
    all(Significant[Outcome %in% c("Trust", "Understanding", "Relevance")] == FALSE)
)

if (isTRUE(only_consistency_sig)) {

  wide_delta <- df %>%
    dplyr::select(id, type_of_explanation, trust, consistency) %>%
    tidyr::pivot_wider(
      names_from = type_of_explanation,
      values_from = c(trust, consistency),
      names_sep = "_"
    ) %>%
    janitor::clean_names() %>%
    dplyr::mutate(
      d_trust = trust_co_t - trust_non_co_t,
      d_consistency = consistency_co_t - consistency_non_co_t
    ) %>%
    dplyr::filter(stats::complete.cases(d_trust, d_consistency))

  assoc_lm <- stats::lm(d_trust ~ d_consistency, data = wide_delta)

  assoc_tbl <- broom::tidy(assoc_lm, conf.int = TRUE) %>%
    dplyr::mutate(
      Outcome = "Trust (Δ CoT–Non-CoT)",
      Predictor = dplyr::recode(term,
        "(Intercept)" = "Intercept",
        "d_consistency" = "Consistency (Δ CoT–Non-CoT)"
      )
    ) %>%
    dplyr::rename(
      Estimate = estimate,
      SE = std.error,
      T_value = statistic,
      P_value = p.value,
      CI_Lower = conf.low,
      CI_Upper = conf.high
    ) %>%
    dplyr::select(Outcome, Predictor, Estimate, SE, CI_Lower, CI_Upper, T_value, P_value)

  readr::write_csv(
    assoc_tbl,
    "outputs/tables/Exploratory_Association_DeltaTrust_DeltaConsistency.csv"
  )

  assoc_tbl

} else {
  message("Exploratory association model not executed (pattern 'only Consistency significant' not met).")
}

print(names(wide_delta))

# ============================================================
# Optional figure: ΔTrust vs ΔConsistency
# ============================================================

if (isTRUE(only_consistency_sig)) {

  p_assoc <- ggplot2::ggplot(wide_delta, ggplot2::aes(x = d_consistency, y = d_trust)) +
    ggplot2::geom_point() +
    ggplot2::geom_smooth(method = "lm", se = TRUE) +
    ggplot2::labs(
      title = "Association between within-person changes",
      x = "Δ Consistency (CoT – Non-CoT)",
      y = "Δ Trust (CoT – Non-CoT)"
    )

  ggplot2::ggsave(
    "outputs/figures/Figure_Exploratory_DeltaTrust_DeltaConsistency.png",
    p_assoc,
    width = 7, height = 5, dpi = 300
  )

  p_assoc
}

"""**Exploratory within-person association.**\

An exploratory analysis examined whether within-person changes in perceived consistency were associated with within-person changes in trust (ΔCoT–ΔNon-CoT). A one-point increase in *Consistency* (ΔCoT–ΔNon-CoT) was associated with a 0.76-point increase in Trust (β = 0.76, 95% CI 0.45–1.06, p = 1.1×10⁻⁵). The intercept was not statistically different from zero (p = 0.54), indicating no systematic change in trust when changes in consistency were absent.

## **Discussion**

> Although CoT did not increase trust on average, participants who perceived greater improvements in consistency tended to also report greater improvements in trust.

"""

# Figure: ΔTrust vs ΔConsistency (journal style)

if (isTRUE(only_consistency_sig)) {

  p_assoc <- ggplot2::ggplot(
    wide_delta,
    ggplot2::aes(x = d_consistency, y = d_trust)
  ) +
    ggplot2::geom_point(
      color = "#1F77B4",
      size = 2.5,
      alpha = 0.75
    ) +
    ggplot2::geom_smooth(
      method = "lm",
      se = TRUE,
      color = "#D62728",
      fill = "#D62728",
      alpha = 0.15,
      linewidth = 1
    ) +
    ggplot2::labs(
      title = "Within-person association between changes in Consistency and Trust",
      subtitle = "Differences computed as CoT − Non-CoT",
      x = "Δ Consistency (CoT − Non-CoT)",
      y = "Δ Trust (CoT − Non-CoT)"
    ) +
    ggplot2::theme_minimal(base_size = 13) +
    ggplot2::theme(
      plot.title = ggplot2::element_text(face = "bold"),
      panel.grid.minor = ggplot2::element_blank()
    )

  ggplot2::ggsave(
    "outputs/figures/Figure_Exploratory_DeltaTrust_DeltaConsistency.png",
    p_assoc,
    width = 7, height = 5, dpi = 300
  )

  p_assoc
}

p_assoc <- ggplot2::ggplot(
  wide_delta,
  ggplot2::aes(x = d_consistency, y = d_trust)
) +
  ggplot2::geom_point(
    aes(color = d_consistency),
    size = 3,
    alpha = 0.8
  ) +
  ggplot2::scale_color_viridis_c(option = "D") +
  ggplot2::geom_smooth(
    method = "lm",
    se = TRUE,
    color = "black",
    fill = "gray70",
    linewidth = 1
  ) +
  ggplot2::labs(
    title = "Association between changes in Consistency and Trust",
    x = "Δ Consistency (CoT − Non-CoT)",
    y = "Δ Trust (CoT − Non-CoT)",
    color = "Δ Consistency"
  ) +
  ggplot2::theme_classic(base_size = 13) +
  ggplot2::theme(
    plot.title = ggplot2::element_text(hjust = 0.5)
  )

p_assoc

# Save the image (journal-ready)
ggplot2::ggsave(
  filename = "outputs/figures/Figure_Exploratory_DeltaTrust_DeltaConsistency.png",
  plot = p_assoc,
  width = 7,
  height = 5,
  dpi = 300
)

"""**Exploratory within-person association**\

An exploratory analysis examined whether within-person changes in perceived consistency were associated with within-person changes in trust between the CoT and Non-CoT conditions. A greater increase in *Consistency* from Non-CoT to CoT was strongly associated with a greater increase in *Trust* (β = 0.76, 95% CI 0.45–1.06, p \< 0.001). This association was observed despite the absence of a significant average difference in trust between conditions.

**Figure X.** Association between changes in perceived consistency and trust. Each point represents a within-person difference between the CoT and Non-CoT conditions. The solid line represents the linear regression fit, and the shaded area indicates the 95% confidence interval.

"""