# -*- coding: utf-8 -*-
"""Análise do Likert EN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g2u4M3lI6wYp8dZ7_UfZmsuxBn2GdEOz

#  **Analysis of responses on the Likert scale**


**Authors:** Adonias Caetano de Oliveira, Ariel Soares Teles

**Institution:** UFDPar

## **Library installation and environment configuration**
"""

!pip install plot-likert

"""## **Importing library**"""

# Auxiliaries
import pandas as pd
import numpy as np
import io
import re
import plot_likert

"""## **Lendo o datasett**"""

url = 'https://docs.google.com/spreadsheets/d/1YLwadMeQD_hIhSWp82ixTbgioBJifFQ0/edit?usp=sharing&ouid=107874559379957908991&rtpof=true&sd=true'
file_id = url.split('/')[-2]
read_url='https://drive.google.com/uc?id=' + file_id

# read the data
df = pd.read_excel(read_url, sheet_name='respostas')
df

another_scale = ['Strongly Disagree', 'Partially Disagree', 'Neutral / Indifferent', 'Partially Agree', 'Strongly Agree']

df.replace({
    1: 'Strongly Disagree',
    2: 'Partially Disagree',
    3: 'Neutral / Indifferent',
    4: 'Partially Agree',
    5: 'Strongly Agree'
}, inplace=True)

df

plot_likert.plot_likert(df, another_scale,  figsize=(10,10), bar_labels=True, bar_labels_color="snow", colors=plot_likert.colors.default_with_darker_neutral);

plot_likert.plot_likert(df, another_scale,  figsize=(10,10), bar_labels=True, bar_labels_color="snow", colors=plot_likert.colors.default_with_darker_neutral, plot_percentage=True);